### ISSUE TITLE
Flagged by Windows Defender

### ISSUE THREAD

**Issue by admiralspeedy** [mrdude2478/IPS_Patch_Creator#5] opened 2023-03-16 04:18 UTC
This program is flagged as several different viruses by Windows Defender, which rates it as a major threat and immediately quarantines the app.

**Comment by Dimensional** [comment] 2023-03-16 09:59
I'm getting the same thing with BitDefender, even when attempting to compile the source. VirusTotal isn't able to flag the link itself, but when downloading on another PC and then uploading, it's getting 23 out of 61 flags. What's happening?

**Comment by mrdude2478** [comment] 2023-03-16 16:11
Read the source, you can edit it however you want. Maybe you have a virus on your computer from some other sofware you installed that gets run when this program calls on windows api's, however it's not from this program. You can run in a sandbox if you want to test this out. Closing topic as this is nothing to do with this software and this is not a computer helpline.

**Closed by mrdude2478** 2023-03-16 16:11 UTC

**Comment by admiralspeedy** [comment] 2023-03-16 16:23
What an absolutely douche response.

You know it has nothing to do with my computer, the application is flagged on VirusTotal as well and it is caused by some part of your code or a library you are using. I did not say there was a virus in the application, it's almost certainly false positives but you can submit to Microsoft as the developer to have them look at it and unflag it.

**Comment by Dimensional** [comment] 2023-03-16 16:40
Agreed. I went as far as compiled this on a Windows Virtual Machine on my Linux Server, and still got flagged. So the developer's response is misguided and apparently hostile, when we are just wanting to understand why the program is getting flagged. Maybe there's a section of code that happens to do similar processes that most malware does? We're asking for clarity here. Please, help us understand what the probable cause is. It's your program, you know it better than the rest of us.

**Comment by admiralspeedy** [comment] 2023-03-16 16:42
That's good to know because I was about to build it myself and check if it gets flagged (to see if he uploaded a modified malicious version as a release).

I am now working my way through the source and seeing what VirusTotal can tell me.

**Comment by Dimensional** [comment] 2023-03-16 17:04
I'd say still test, for thoroughness. 1 person getting a positive on a clean machine could be a fluke. 2 people on separate clean machines, especially newly installed VMs, that would indicate something else. I just hope the cause isn't actually nefarious but just something this program does that gets flagged as something else. Really have hopes for this, despite getting these flags.

**Comment by mrdude2478** [comment] 2023-03-17 21:39
> What an absolutely douche response.
> 
> You know it has nothing to do with my computer, the application is flagged on VirusTotal as well and it is caused by some part of your code or a library you are using. I did not say there was a virus in the application, it's almost certainly false positives but you can submit to Microsoft as the developer to have them look at it and unflag it.
> 
> The fact that you have responded this way leads me to believe that you are actually doing something suspicious with this tool now.

Make your own software then.

**Comment by FandrewDavid** [comment] 2024-02-25 23:19
> I'd say still test, for thoroughness. 1 person getting a positive on a clean machine could be a fluke. 2 people on separate clean machines, especially newly installed VMs, that would indicate something else. I just hope the cause isn't actually nefarious but just something this program does that gets flagged as something else. Really want it to be just false positives and we're over reacting.

Was it ever confirmed to be a false positive, I would imagine it would be of course but you could never be too safe even if I look silly in the end.
